export default {
  active: null,
  click_active: { current: {}, last: {}, position: { top: 0, left: 0 } },
  list: [
    {
      id: 542,
      title: 'code',
      user_id: 19,
      team_id: 1,
      folder_id: 482,
      created_at: '2018-05-21 14:44:11',
      updated_at: '2018-07-12 13:15:47',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      renamed_title: 'code',
      shares_count: 1,
      is_shortcut: true,
      shortcut_id: 93
    },
    {
      id: 470,
      title: 'Folder 1',
      user_id: 11,
      team_id: 1,
      folder_id: 482,
      created_at: '2018-04-24 12:56:14',
      updated_at: '2018-07-26 11:54:45',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: true,
      has_shared_children: true,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 1
    },
    {
      id: 481,
      title: 'Folder 10',
      user_id: 11,
      team_id: 1,
      folder_id: 482,
      created_at: '2018-04-27 12:09:59',
      updated_at: '2018-07-16 15:25:09',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: true,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 1
    },
    {
      id: 548,
      title: 'yo',
      user_id: 19,
      team_id: 1,
      folder_id: 493,
      created_at: '2018-05-21 14:48:01',
      updated_at: '2018-07-12 13:15:47',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      renamed_title: 'yo',
      shares_count: 1,
      is_shortcut: true,
      shortcut_id: 87
    },
    {
      id: 550,
      title: 'yo yo yo',
      user_id: 19,
      team_id: 1,
      folder_id: 505,
      created_at: '2018-05-21 14:48:21',
      updated_at: '2018-07-12 13:15:47',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      renamed_title: 'yo yo yo',
      shares_count: 1,
      is_shortcut: true,
      shortcut_id: 85
    },
    {
      id: 715,
      title: 'Sofia super',
      user_id: 11,
      team_id: 1,
      folder_id: 505,
      created_at: '2018-07-26 16:22:46',
      updated_at: '2018-07-27 14:14:24',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false
    },
    {
      id: 716,
      title: 'Sogoq1',
      user_id: 11,
      team_id: 1,
      folder_id: 505,
      created_at: '2018-07-26 16:23:03',
      updated_at: '2018-07-27 09:54:38',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: -1,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 1
    },
    {
      id: 685,
      title: 'code',
      user_id: 11,
      team_id: 1,
      folder_id: 676,
      created_at: '2018-06-26 09:20:51',
      updated_at: '2018-07-12 13:15:48',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 1
    },
    {
      id: 686,
      title: 'document',
      user_id: 11,
      team_id: 1,
      folder_id: 676,
      created_at: '2018-06-26 09:20:56',
      updated_at: '2018-06-26 09:20:56',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false
    },
    {
      id: 677,
      title: 'icomoon_1_icons',
      user_id: 11,
      team_id: 1,
      folder_id: 676,
      created_at: '2018-06-26 09:20:34',
      updated_at: '2018-06-26 09:20:34',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 678,
      title: 'icomoon_3_icons',
      user_id: 11,
      team_id: 1,
      folder_id: 676,
      created_at: '2018-06-26 09:20:34',
      updated_at: '2018-06-26 09:20:34',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 688,
      title: 'code',
      user_id: 11,
      team_id: 1,
      folder_id: 686,
      created_at: '2018-06-26 09:20:57',
      updated_at: '2018-06-26 09:20:57',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false
    },
    {
      id: 687,
      title: 'images',
      user_id: 11,
      team_id: 1,
      folder_id: 686,
      created_at: '2018-06-26 09:20:57',
      updated_at: '2018-06-26 09:20:57',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false
    },
    {
      id: 689,
      title: 'video',
      user_id: 11,
      team_id: 1,
      folder_id: 688,
      created_at: '2018-06-26 09:20:59',
      updated_at: '2018-06-26 09:20:59',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false
    },
    {
      id: 661,
      title: '111222',
      user_id: 30,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-06-15 15:09:47',
      updated_at: '2018-07-12 13:15:48',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      renamed_title: '111222',
      shares_count: 2,
      is_shortcut: true,
      shortcut_id: 90
    },
    {
      id: 493,
      title: 'DDDD 33',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-05-08 13:31:13',
      updated_at: '2018-07-27 13:50:11',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 5,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false,
      folder: null
    },
    {
      id: 482,
      title: 'Folder 122',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-27 12:12:11',
      updated_at: '2018-07-30 10:10:01',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 20,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false,
      folder: null
    },
    {
      id: 471,
      title: 'Folder 2',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-24 12:56:20',
      updated_at: '2018-07-30 09:37:01',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 1,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 472,
      title: 'Folder 3',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-24 12:56:42',
      updated_at: '2018-07-27 13:50:11',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 473,
      title: 'Folder 4',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-24 12:56:51',
      updated_at: '2018-07-16 15:25:06',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 1,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 474,
      title: 'Folder 5',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-27 11:57:29',
      updated_at: '2018-04-27 11:57:29',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 478,
      title: 'Folder 6',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-27 12:08:17',
      updated_at: '2018-04-27 12:08:17',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 475,
      title: 'Folder 6',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-27 11:57:39',
      updated_at: '2018-04-27 11:57:39',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 476,
      title: 'Folder 7',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-27 11:57:49',
      updated_at: '2018-04-27 11:57:49',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 479,
      title: 'Folder 8',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-27 12:09:39',
      updated_at: '2018-04-27 12:09:39',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 480,
      title: 'Folder 9',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-27 12:09:49',
      updated_at: '2018-07-26 16:31:41',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 3,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 643,
      title: 'Foll',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-06-15 09:28:18',
      updated_at: '2018-07-27 11:53:24',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 1,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 712,
      title: 'Foogee folder',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-07-26 16:19:04',
      updated_at: '2018-07-27 11:47:27',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 1,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 713,
      title: 'Foogee second folder',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-07-26 16:20:38',
      updated_at: '2018-07-26 16:20:38',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 494,
      title: 'Ge',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-05-08 13:31:35',
      updated_at: '2018-07-27 12:56:51',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: -4,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 737,
      title: 'My camera',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-07-30 13:37:26',
      updated_at: '2018-07-30 13:57:15',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 467,
      title: 'My folder',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-04-24 12:55:44',
      updated_at: '2018-07-12 13:15:46',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 1
    },
    {
      id: 736,
      title: 'My photos ||',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-07-30 13:19:26',
      updated_at: '2018-07-30 13:41:40',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 709,
      title: 'New root 1',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-07-25 14:21:22',
      updated_at: '2018-07-25 15:13:50',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 676,
      title: 'Only folders',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-06-26 09:20:15',
      updated_at: '2018-07-27 09:56:07',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 5,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false,
      folder: null
    },
    {
      id: 505,
      title: 'Sof sofia',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      root: true,
      created_at: '2018-05-15 16:48:10',
      updated_at: '2018-07-27 14:14:35',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 5,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0,
      in_shared: false,
      folder: null
    }
  ],
  collapsed: {},
  selected: {
    start: null,
    list: []
  },
  rootOpen: true
};
