export default {
  folders: [
    {
      id: 661,
      title: '111222',
      user_id: 30,
      team_id: 1,
      folder_id: null,
      created_at: '2018-06-15 15:09:47',
      updated_at: '2018-07-12 13:15:48',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      renamed_title: '111222',
      shares_count: 2,
      is_shortcut: true,
      shortcut_id: 90
    },
    {
      id: 493,
      title: 'DDDD 33',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      created_at: '2018-05-08 13:31:13',
      updated_at: '2018-07-27 13:50:11',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 5,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 3
    },
    {
      id: 482,
      title: 'Folder 122',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      created_at: '2018-04-27 12:12:11',
      updated_at: '2018-07-30 09:36:30',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 19,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 471,
      title: 'Folder 2',
      user_id: 11,
      team_id: 1,
      folder_id: null,
      created_at: '2018-04-24 12:56:20',
      updated_at: '2018-07-30 09:37:01',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: false,
      has_shared_children: true,
      shared_children_count: 1,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    }
  ],
  path: [],
  parent: null
};
