export default {
  folders: [
    {
      id: 542,
      title: 'code',
      user_id: 19,
      team_id: 1,
      folder_id: 482,
      created_at: '2018-05-21 14:44:11',
      updated_at: '2018-07-12 13:15:47',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: false,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      renamed_title: 'code',
      shares_count: 1,
      is_shortcut: true,
      shortcut_id: 93
    },
    {
      id: 496,
      title: 'ffff132',
      user_id: 11,
      team_id: 1,
      folder_id: 482,
      created_at: '2018-05-08 13:38:32',
      updated_at: '2018-07-16 15:25:09',
      deleted_at: null,
      is_shared: false,
      has_shared_parent: true,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 0
    },
    {
      id: 481,
      title: 'Folder 10',
      user_id: 11,
      team_id: 1,
      folder_id: 482,
      created_at: '2018-04-27 12:09:59',
      updated_at: '2018-07-16 15:25:09',
      deleted_at: null,
      is_shared: true,
      has_shared_parent: true,
      has_shared_children: false,
      shared_children_count: 0,
      lockable_id: null,
      locked: null,
      is_locked: null,
      shares_count: 1
    }
  ],
  path: [{ id: 482, title: 'Folder 122', folder_id: null, in_shared: false }],
  parent: {
    id: 482,
    title: 'Folder 122',
    user_id: 11,
    team_id: 1,
    folder_id: null,
    created_at: '2018-04-27 12:12:11',
    updated_at: '2018-07-30 10:10:01',
    deleted_at: null,
    is_shared: false,
    has_shared_parent: false,
    has_shared_children: true,
    shared_children_count: 20,
    shares_count: 0,
    folder: null
  }
};
